#if !canImport(ObjectiveC)
import XCTest

extension GreetingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GreetingTests = [
        ("testGreetings", testGreetings),
    ]
}

extension TimeZoneTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TimeZoneTests = [
        ("testTimeZoneIdentifiersInvalid", testTimeZoneIdentifiersInvalid),
        ("testTimeZoneIdentifiersValid", testTimeZoneIdentifiersValid),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    [
        testCase(GreetingTests.__allTests__GreetingTests),
        testCase(TimeZoneTests.__allTests__TimeZoneTests),
    ]
}
#endif
