#if !canImport(ObjectiveC)
import XCTest

extension AWSXRayRecorderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AWSXRayRecorderTests = [
        ("testRecordingOneSegmentNoEnding", testRecordingOneSegmentNoEnding),
        ("testRecordingOneSegmentWithEnding", testRecordingOneSegmentWithEnding),
        ("testRecordingTwoSegmentNoEnding", testRecordingTwoSegmentNoEnding),
    ]
}

extension AWSXRaySegmentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AWSXRaySegmentTests = [
        ("testSegmentRandomId", testSegmentRandomId),
        ("testTraceRandomId", testTraceRandomId),
        ("testTraceRandomIdenifier", testTraceRandomIdenifier),
        ("testTracingHeaderValueInvalid", testTracingHeaderValueInvalid),
        ("testTracingHeaderValueRootNoParent", testTracingHeaderValueRootNoParent),
        ("testTracingHeaderValueRootWithParent", testTracingHeaderValueRootWithParent),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AWSXRayRecorderTests.__allTests__AWSXRayRecorderTests),
        testCase(AWSXRaySegmentTests.__allTests__AWSXRaySegmentTests),
    ]
}
#endif
