name: Lint

on: [push]

jobs:

  lint:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install swiftformat
      run: brew install swiftformat
    - name: Run lint
      run: swiftformat --lint .
