name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test-macos:
    runs-on: macos-latest  

    steps:
    - uses: actions/checkout@v2
    - name: OS name
      run: uname -a
    - name: Swift version
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

  test-linux:
    strategy:
      matrix:
        images:
        # - swift:5.2
        - swift:5.2-amazonlinux2
        - swift:nightly-5.3-bionic
    container:
      image: ${{ matrix.images }}
    steps:
    - uses: actions/checkout@v2
    - name: Swift version
      run: swift --version
    - name: Run tests
      run: swift test --enable-test-discovery
